# Experiment 2
## NUMERICAL PYTHON (NUMPY)

### NORMALIZATION PROBLEM

In [143]:
#Access numpy library
import numpy as np

#Create a randomly-generated 5x5 array called X
X = np.random.random((5,5))

#Formulate the equation for Normalization
mean = X.mean()
std = X.std()
Z = (X - mean) / std

#Save normalized array
np.save('X_normalized.npy', Z)

#Print arrays
print("Random Array: \n", X)
print("\nNormalized Array: \n", Z)

Random Array: 
 [[0.09178159 0.39904617 0.25093973 0.24806746 0.02456346]
 [0.97752012 0.0855163  0.70840563 0.22061908 0.58080502]
 [0.9176351  0.55674851 0.73556237 0.79262935 0.3183263 ]
 [0.98180332 0.56966275 0.11557885 0.23521543 0.23959007]
 [0.24689929 0.33662758 0.98231746 0.04098579 0.74840671]]

Normalized Array: 
 [[-1.15740897 -0.18155023 -0.65192975 -0.66105195 -1.37089079]
 [ 1.65565746 -1.17730726  0.80096174 -0.74822679  0.39570786]
 [ 1.46546529  0.31930543  0.88721035  1.06845255 -0.43791299]
 [ 1.66926074  0.36032047 -1.08182993 -0.70186942 -0.68797576]
 [-0.66476199 -0.37978891  1.67089362 -1.31873417  0.9280034 ]]


### DIVISIBLE BY 3 PROBLEM

In [139]:
#Access numpy library
import numpy as np

#Create array of first 100 positive integers
INT = np.arange(1,101,1) 

#Make an array of the square of INT
square = INT**2

#Reshape A as a 10x10 array
A = square.reshape((10,10))

#Determine which elements are divisible by 3
DB3 = A[A % 3 == 0]

#Save array as  div_by_3.npy
np.save('div_by_3.npy', DB3)

#Print arrays
print("A =\n", A)
print ("\nElements divisible by 3: \n", DB3) 


A =
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
